# render.yaml
services:
  - type: web
    name: marketpulse-new-real-3-web
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: cd src/backend && PYTHONPATH=. gunicorn --bind 0.0.0.0:$PORT main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: SECRET_KEY
        value: fb4f4f255fb38f23a4d7379be97c837b
      - key: DATABASE_URL
        value: postgresql://finals2:kHp9MSWHJpK7XhrzAbvKCosZDxKzPkC3@dpg-d0e4k6h5pdvs73ao5d2g-a.oregon-postgres.render.com/finals2
      - key: DB_HOST
        value: dpg-d0e4k6h5pdvs73ao5d2g-a.oregon-postgres.render.com
      - key: DB_USER
        value: finals2
      - key: DB_PASSWORD
        value: kHp9MSWHJpK7XhrzAbvKCosZDxKzPkC3
      - key: DB_NAME
        value: finals2
      - key: DB_PORT
        value: 5432
      - key: FRONTEND_URL
        value: https://marketpulse-new-real-3.onrender.com
      # Email configuration
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: EMAIL_USERNAME
        value: norbertcabasag999@gmail.com  # Replace with your actual Gmail address
      - key: EMAIL_PASSWORD
        value: ojznuvzdasgbkggy  # Replace with your app password (not your regular password)
      - key: DEFAULT_FROM_EMAIL
        value: norbertcabasag999@gmail.com
  
  - type: web
    name: marketpulse-new-real-3
    env: static
    region: oregon
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-store
    envVars:
      - key: REACT_APP_API_URL
        value: https://marketpulse-new-real-3-web.onrender.com/api

# Using existing database instead of creating a new one
# databases:
#   - name: marketpulse-db
#     region: ohio
#     plan: free
#     databaseName: finals 