services:
  # Backend service as Docker
  - type: web
    name: marketpulse-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4

  # Frontend service (if your frontend is separate)
  - type: web
    name: marketpulse-frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16.20.0 